### PR TITLE
309 fixed power prior

### LINKED ISSUE #309: power prior

### PR DESCRIPTION
**Pull request by gravesti**

### CODE REVIEW

File: R/borrowing_fixed_power_prior.R [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+#' @param power_col character. Name of the column containing values to be used as the power parameters.
+#'
+#' @return Object of class [`BorrowingFixedPowerPrior`][BorrowingFixedPowerPrior-class].
+#' @export
+#' @examples
+#' borrowing_fixed_power_prior(
+#'   ext_flag_col = "ext",
+#'   power_col = "power"
+#' )
+borrowing_fixed_power_prior <- function(ext_flag_col, power_col) {
```
Comment (mattsecrest) [inline R/borrowing_fixed_power_prior.R]: @gravesti What about some checking that power_col is [0,1] here as well? I see in STAN but maybe the error would be cryptic?

**Comment by mattsecrest** [comment]
@gravesti looks good. Was a bit surprised to see a vector of weights, as the fixed power prior is typically one weight for all the external data, right? (And I see that the test cases are doing this already). I guess there is no downside to doing it this way because it is more flexible and we can use it for eg IPTW weights. 

Seeing now that the stan templates is annoying, but still I bet this is the best approach.

**Review by mattsecrest — APPROVED** [review]

File: R/borrowing_fixed_power_prior.R (hunk 1 above)
Comment (gravesti) [reply R/borrowing_fixed_power_prior.R]: We don't have the data here. I will add it in `prepare_stan_data_inputs`

**Comment by gravesti** [comment]
> Was a bit surprised to see a vector of weights, as the fixed power prior is typically one weight for all the external data, right? (And I see that the test cases are doing this already). I guess there is no downside to doing it this way because it is more flexible and we can use it for eg IPTW weights.

Yeah, we could go for specifying a number directly: `borrowing_fixed_power_prior("ext", power = 0.7)`
and then set that for the external subjects and the rest to 1.

**Comment by gravesti** [comment]
@mattsecrest I've changed to a single `power_par` value specified directly. Let me know what you think.

File: R/borrowing_fixed_power_prior.R (hunk 1 above)
Comment (gravesti) [reply R/borrowing_fixed_power_prior.R]: We now just have a single value, so can assert here.

**Comment by mattsecrest** [comment]
@gravesti looks good! I like the templates in `inst/stan` more and more. There's one line that might be too clever?

```
power <- 1 - (1 - borrowing@power_par) * data_matrix[, borrowing@ext_flag_col]
```

Maybe this?

```
power <- rep(1, nrow(data_matrix))
power[data_matrix[, borrowing@ext_flag_col] == 1] <- borrowing@power_par
```

Before we submit:

- [x] update vignettes
- [x] CI/CD pass

**Comment by mattsecrest** [comment]
Addresses #309
